services:
  gebler_security_headers.response_subscriber:
    class: Gebler\SecurityHeadersBundle\EventSubscriber\ResponseSubscriber
    arguments:
      $parameterBag: "@parameter_bag"
    tags:
      - { name: kernel.event_subscriber }